spring:
  application:
    name: security
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo-teach
    username: postgres
    password: root
  jpa:
    hibernate.ddl-auto: update

security:
  cors: ${FRONT-END}
  secret: ${SECRET}